// <auto-generated />
using System;
using Accrual.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accrual.Api.Data.Migrations
{
    [DbContext(typeof(AccrualDb))]
    partial class AccrualDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accrual.Api.Data.CommissionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BeneficiaryExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("beneficiary_external_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid?>("PayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("payout_id");

                    b.Property<string>("SchemaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("schema_type");

                    b.HasKey("Id")
                        .HasName("pk_commissions");

                    b.HasIndex("PayoutId")
                        .HasDatabaseName("ix_commissions_payout_id");

                    b.HasIndex("EventId", "Level")
                        .IsUnique()
                        .HasDatabaseName("ix_commissions_event_id_level");

                    b.ToTable("commissions", (string)null);
                });

            modelBuilder.Entity("Accrual.Api.Data.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DispatchToken")
                        .HasColumnType("uuid")
                        .HasColumnName("dispatch_token");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_message_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_status_next_attempt_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Accrual.Api.Data.ProfitEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CalculationAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("calculation_attempts");

                    b.Property<DateTimeOffset?>("CalculationStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculation_started_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<DateTimeOffset>("NextCalculationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_calculation_at");

                    b.Property<decimal>("Profit")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("profit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("UserExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_external_id");

                    b.HasKey("Id")
                        .HasName("pk_profit_events");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_profit_events_external_id");

                    b.HasIndex("Status", "NextCalculationAt")
                        .HasDatabaseName("ix_profit_events_status_next_calculation_at");

                    b.ToTable("profit_events", (string)null);
                });

            modelBuilder.Entity("Accrual.Api.Data.SchemaSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("SchemaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("schema_type");

                    b.HasKey("Id")
                        .HasName("pk_schema_settings");

                    b.ToTable("schema_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SchemaType = "Linear"
                        });
                });

            modelBuilder.Entity("Accrual.Api.Data.CommissionLine", b =>
                {
                    b.HasOne("Accrual.Api.Data.ProfitEvent", "Event")
                        .WithMany("Commissions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commissions_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Accrual.Api.Data.ProfitEvent", b =>
                {
                    b.Navigation("Commissions");
                });
#pragma warning restore 612, 618
        }
    }
}
